### PR TITLE
fix: Maintain original list order when clearing search input

### LINKED ISSUE #32: Bug: Search items not always returned to original order after searching
I've noticed the `Command.Item` components will be render in a seemingly random order sometimes when searching and resetting the filter.

Reproduction:
1. Use the Raycast menu on cmdk-sv.com
2. Type a random letter (e.g. "I") and press backspace repeatedly in quick succession until the order changes.
3. The "unfiltered" results result is sorted by some seemingly random order

Screen Recording 2023-11-18 at 9 52 28 pm

### PR DESCRIPTION
**Pull request by Not-Jayden**
Closes #32 

Not super confident in this as the optimal solution so please sanity check it for me.

### CODE REVIEW

File: src/lib/cmdk/components/CommandList.svelte [hunk 1]
```diff
@@ -56,11 +57,15 @@
 </script>
 
 {#if asChild}
-	<slot {list} {sizer} />
+	{#key $state.search === ''}
```
Comment (Not-Jayden) [inline src/lib/cmdk/components/CommandList.svelte:60]: I originally had this wrapping the entire component but that was causing a flicker in animations, so I've instead duplicated it above the default slot.

I think there's a risk this will cause unwanted animations on the items inside the list though 😕

**Review by huntabyte — APPROVED** [review]

**Comment by huntabyte** [comment]
Thank you!
